go_import_path: github.com/influxdata/telegraf
language: go

os:
  - linux
  
go:
  - "1.12.x"

script:
  - cd $TRAVIS_BUILD_DIR; make

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
