struct Tag {
    string key;
    string value;
};

enum FieldKind{
    FIELD_DOUBLE,
    FIELD_INT,
    FIELD_UINT,
    FIELD_STRING,
    FIELD_BOOL
};

union FieldValue switch (FieldKind) {
    case FIELD_DOUBLE:
        double d;
    case FIELD_INT:
        long long i;
    case FIELD_UINT:
        unsigned long long u;
    case FIELD_STRING:
        string s;
    case FIELD_BOOL:
        boolean b;
};

struct Field {
    string key;
    FieldKind kind;
    FieldValue value;
};

const long MAX_TAGS = 32;
const long MAX_FIELDS = 128;

struct Metric {
    string name;//@key
    sequence<Tag, MAX_TAGS> tags;
    sequence<Field, MAX_FIELDS> fields;
    long long timestamp;
};
